// Organisation and simultaneous fits: reading and using a workspace

// The INPUT file for this macro is generated by rf502_wspacewrite.C

#include "RooRealVar.h"
#include "RooDataSet.h"
#include "RooGaussian.h"
#include "RooChebychev.h"
#include "RooAddPdf.h"
#include "RooWorkspace.h"
#include "RooPlot.h"
#include "TCanvas.h"
#include "TLegend.h"
#include "TAxis.h"
#include "TFile.h"
#include "TH1.h"
using namespace RooFit;
 
void rf503_wspaceread()
{
   // R e a d   w o r k s p a c e   f r o m   f i l e
   // -----------------------------------------------
 
   // Open input file with workspace (generated by rf502_wspacewrite)
   TFile *f = new TFile("rf502_workspace.root");
 
   // Retrieve workspace from file
   RooWorkspace *w = (RooWorkspace *)f->Get("w");
 
   // R e t r i e v e   p d f ,   d a t a   f r o m   w o r k s p a c e
   // -----------------------------------------------------------------
 
   // Retrieve x, model and data from workspace
   RooRealVar *x     = w->var("x");
   RooAbsPdf  *model = w->pdf("model");
   RooAbsData *data  = w->data("modelData");
 
   // Print structure of composite pdf
   std::cout << "\n Print structure of composite pdf \n" << endl;
   model->Print("t");
 
   // F i t   m o d e l   t o   d a t a ,   p l o t   m o d e l
   // ---------------------------------------------------------
 
   // Fit model to data
   std::cout << "\n Fit model to data \n" << endl;
   model->fitTo(*data, PrintLevel(-1));
 
   // Plot data and PDF overlaid
   TCanvas *c = new TCanvas("c", "Model and data read from workspace");

   c->SetCanvasSize(2490, 1400);
   c->SetWindowSize(2500, 1500);

   RooPlot *xframe = x->frame(Title("Model and data read from workspace"));
   data->plotOn(xframe);
   model->plotOn(xframe, LineStyle(1)); // 1 = kSolid

   // Overlay the sig1 components of model
   model->plotOn(xframe, Components("sig1"), LineStyle(3)); // 3 = kDotted

   // Overlay the sig2 components of model
   model->plotOn(xframe, Components("sig2"), LineStyle(9));

   // Overlay the sig1+sig2 components of model
   model->plotOn(xframe, Components("sig1,sig2"), LineStyle(10));

   // Overlay the background component of model with a dashed line
   model->plotOn(xframe, Components("bkg"), LineStyle(2)); // 2 = kDashed

   xframe->Draw();

   c->Print("rf503_wspaceread.png");
}